image: node:14

stages:
  - build
  - deploy

# Job para construir o projeto
build:
  stage: build
  script:
    - npm install 
    - echo "Build do projeto conclu√≠do!" 
  artifacts:
    paths:
      - dist/ 

# Job para servir o site
deploy:
  stage: deploy
  script:
    - npm install -g http-server 
    - http-server . -p 8080 
  only:
    - main 
  environment:
    name: production
    url: http://$CI_PROJECT_NAME.gitlab.io 
